[theme]
primaryColor = "#7D1B5D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F2F5"
textColor = "#33353A"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[server]
enableStaticServing = true